### ISSUE TITLE
Frage: Wichtig! Adapter vor dem Update löschen

### ISSUE THREAD

**Issue by capitaenz** [Jey-Cee/ioBroker.deconz#142]
Hallo zusammen,

wenn ich den Adapter lösche wie empfohlen, verliere ich dann alle Objekte und muss diese in den Skripts/Blocky wieder alle aktualisieren?
Aktuell verwende ich  deConz ZigBee  1.3.4
Mein System sieht wie folgt aus:
Tinkerboard S
Node.js v12.16.2
NPM 6.14.4
JS Controller 3.0.18

Danke und VG
Leif

**Comment by Jey-Cee** [comment]
Nein deine Skripte bleiben unverändert. Die Objekte werden neu angelegt, behalten aber ihre id. Das ist nötig weil die Objektdefinitionen für ein paar Objekte angepasst wurden.
Und gerade wenn man von älteren Versionen kommt, passiert es häufig das die Konfiguration nicht ordentlich angelegt bzw. Die alte überschrieben wird.

**Comment by capitaenz** [comment]
@Jey-Cee OK, danke für den Hinweis.
Aus Interesse, wo werden denn die id's abgespeichert, wenn doch der Adapter gelöscht wurde?

**Comment by Mr-REM-Esq** [comment]
Sorry, but I would like to clarify. Do I understand correctly that I need to remove the adapter using the button, and then install it again?

![Снимок экрана 2020-05-07 в 21 49 51](https://user-images.githubusercontent.com/42520242/81333921-e68d8e00-90ad-11ea-8387-782afe53efea.png)

**Comment by Jey-Cee** [comment]
Yes correct but wait until tomorrow, there is aproblem with 1.3.6 and i have removed it.
Tomorrow is 1.3.7 available.

**Comment by Mr-REM-Esq** [comment]
Thank you for your comment.

**Comment by Jey-Cee** [comment]
> @Jey-Cee OK, danke für den Hinweis.
> Aus Interesse, wo werden denn die id's abgespeichert, wenn doch der Adapter gelöscht wurde?

Die ids werden von deconz vergeben und auch dort gespeichert. Der Adaptert holt sich die Daten von dort.

**Comment by capitaenz** [comment]
@Jey-Cee 
Hab den Adapter gelöscht und neu installiert (V 1.3.7) und nun startet er nicht mehr:


```
deconz.0	2020-05-08 08:48:58.078	error	(13183) Error: undefined is not a valid state value at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1581:39 at deconz.setState (/opt/iobroker/node_modules/iobroker.js-control
deconz.0	2020-05-08 08:48:58.076	error	(13183) uncaught exception: undefined is not a valid state value
deconz.0	2020-05-08 08:48:58.076	warn	(13183) This value will not be set in future versions. Please report this to the developer.
deconz.0	2020-05-08 08:48:58.076	warn	(13183) State value to set is invalid for deconz.0.Lights.18.on: The state is missing the required property val!
deconz.0	2020-05-08 08:48:58.075	debug	(13183) Code 200: Request succeded set light state 18: [{"success":{"/lights/18/state/on":false}}]
deconz.0	2020-05-08 08:48:58.068	info	(13183) Terminated (NO_ERROR): Without reason
deconz.0	2020-05-08 08:48:58.067	debug	(13183) Plugin sentry destroyed
deconz.0	2020-05-08 08:48:58.066	info	(13183) terminating
deconz.0	2020-05-08 08:48:58.053	error	(13183) Error: undefined is not a valid state value at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1581:39 at deconz.setState (/opt/iobroker/node_modules/iobroker.js-control
deconz.0	2020-05-08 08:48:58.052	error	(13183) uncaught exception: undefined is not a valid state value
deconz.0	2020-05-08 08:48:58.051	warn	(13183) This value will not be set in future versions. Please report this to the developer.
deconz.0	2020-05-08 08:48:58.050	warn	(13183) State value to set is invalid for deconz.0.Groups.3.on: The state is missing the required property val!
deconz.0	2020-05-08 08:48:58.049	debug	(13183) Code 200: Request succeded set group state 3: [{"success":{"/groups/3/action/on":false}}]
deconz.0	2020-05-08 08:48:57.948	debug	(13183) Websocket connection closed
deconz.0	2020-05-08 08:48:57.928	info	(13183) cleaned everything up...
deconz.0	2020-05-08 08:48:57.924	error	(13183) Error: undefined is not a valid state value at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1581:39 at deconz.setState (/opt/iobroker/node_modules/iobroker.js-control
deconz.0	2020-05-08 08:48:57.893	error	(13183) uncaught exception: undefined is not a valid state value
deconz.0	2020-05-08 08:48:57.888	warn	(13183) This value will not be set in future versions. Please report this to the developer.
deconz.0	2020-05-08 08:48:57.886	warn	(13183) State value to set is invalid for deconz.0.Groups.3.on: The state is missing the required property val!
deconz.0	2020-05-08 08:48:57.884	debug	(13183) Code 200: Request succeded set group state 3: [{"success":{"/groups/3/action/on":false}}]
deconz.0	2020-05-08 08:48:57.816	debug	(13183) Code 200: Request succeded get group attributes 8: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"eta
deconz.0	2020-05-08 08:48:57.810	debug	(13183) Code 200: Request succeded get group attributes 7: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"eta
deconz.0	2020-05-08 08:48:57.802	debug	(13183) Code 200: Request succeded get group attributes 6: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"eta
deconz.0	2020-05-08 08:48:57.794	debug	(13183) Code 200: Request succeded get group attributes 5: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"eta
deconz.0	2020-05-08 08:48:57.776	debug	(13183) Code 200: Request succeded get group attributes 4: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"eta
deconz.0	2020-05-08 08:48:57.757	debug	(13183) dp: on; id:Lights.18 tmp: deconz,0,Lights,18
deconz.0	2020-05-08 08:48:57.757	debug	(13183) stateChange Lights.18 {"val":false,"ack":false,"ts":XXXXXXXX,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":XXXXXXXX}
deconz.0	2020-05-08 08:48:57.750	debug	(13183) Code 200: Request succeded get group attributes 3: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"eta
deconz.0	2020-05-08 08:48:57.744	debug	(13183) Code 200: Request succeded get group attributes 2: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"eta
deconz.0	2020-05-08 08:48:57.736	debug	(13183) Code 200: Request succeded get group attributes 1: {"action":{"bri":127,"colormode":"xy","ct":0,"effect":"none","hue":22084,"on":true,"sat":0,"scene":null,"xy":[0.312718,0.329015]},"devicememb
deconz.0	2020-05-08 08:48:57.730	debug	(13183) dp: on; id:Groups.3 tmp: deconz,0,Groups,3
deconz.0	2020-05-08 08:48:57.729	debug	(13183) stateChange Groups.3 {"val":false,"ack":false,"ts":XXXXXXXX,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":XXXXXXXX}
deconz.0	2020-05-08 08:48:57.694	debug	(13183) dp: on; id:Groups.3 tmp: deconz,0,Groups,3
deconz.0	2020-05-08 08:48:57.694	debug	(13183) stateChange Groups.3 {"val":false,"ack":false,"ts":XXXXXXXX,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":XXXXXXXX}
deconz.0	2020-05-08 08:48:57.065	info	(13183) Code 404: Ressource not found get devices: []
deconz.0	2020-05-08 08:48:57.059	debug	(13183) Code 200: Request succeded get all groups: {"1":{"action":{"bri":127,"colormode":"xy","ct":0,"effect":"none","hue":22084,"on":true,"sat":0,"scene":null,"xy":[0.312718,0.329015]},"devicemembers
deconz.0	2020-05-08 08:48:56.982	debug	(13183) Code 200: Request succeded get all sensors: {"10":{"config":{"battery":100,"on":true,"reachable":true},"ep":1,"etag":"XXXXXXXX","manufacturername":"LUMI","mode":1,"mode
deconz.0	2020-05-08 08:48:56.777	debug	(13183) Code 200: Request succeded get all lights: {"1":{"ctmax":370,"ctmin":151,"etag":"XXXXXXXX","hascolor":true,"manufacturername":"OSRAM","modelid":"Flex RGBW","name":"Wohn
deconz.0	2020-05-08 08:48:56.743	debug	(13183) Subscribed to updates...
deconz.0	2020-05-08 08:48:56.730	info	(13183) deConz Version: 2.5.67; API version: 1.16.0
deconz.0	2020-05-08 08:48:56.728	debug	(13183) Code 200: Request succeded get config: {"UTC":"2020-05-08T06:48:56","apiversion":"1.16.0","backup":{"errorcode":0,"status":"idle"},"bridgeid":"XXXXXXXX","datastoreversion":"60","devic
deconz.0	2020-05-08 08:48:56.592	info	(13183) starting. Version 1.3.7 in /opt/iobroker/node_modules/iobroker.deconz, node: v12.16.2, js-controller: 3.0.18
deconz.0	2020-05-08 08:48:56.442	debug	(13183) Plugin sentry Initialize Plugin (enabled=true)
deconz.0	2020-05-08 08:48:23.682	error	(13165) Error: undefined is not a valid state value at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1581:39 at deconz.setState (/opt/iobroker/node_modules/iobroker.js-control
deconz.0	2020-05-08 08:48:23.681	error	(13165) uncaught exception: undefined is not a valid state value
deconz.0	2020-05-08 08:48:23.680	warn	(13165) This value will not be set in future versions. Please report this to the developer.
deconz.0	2020-05-08 08:48:23.680	warn	(13165) State value to set is invalid for deconz.0.Lights.18.on: The state is missing the required property val!
deconz.0	2020-05-08 08:48:23.679	debug	(13165) Code 200: Request succeded set light state 18: [{"success":{"/lights/18/state/on":false}}]
deconz.0	2020-05-08 08:48:23.671	error	(13165) Error: undefined is not a valid state value at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1581:39 at deconz.setState (/opt/iobroker/node_modules/iobroker.js-control
deconz.0	2020-05-08 08:48:23.669	error	(13165) uncaught exception: undefined is not a valid state value
deconz.0	2020-05-08 08:48:23.668	warn	(13165) This value will not be set in future versions. Please report this to the developer.
deconz.0	2020-05-08 08:48:23.668	warn	(13165) State value to set is invalid for deconz.0.Groups.3.on: The state is missing the required property val!
deconz.0	2020-05-08 08:48:23.667	debug	(13165) Code 200: Request succeded set group state 3: [{"success":{"/groups/3/action/on":false}}]
deconz.0	2020-05-08 08:48:23.654	error	(13165) Error: undefined is not a valid state value at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1581:39 at deconz.setState (/opt/iobroker/node_modules/iobroker.js-control
deconz.0	2020-05-08 08:48:23.652	error	(13165) uncaught exception: undefined is not a valid state value
deconz.0	2020-05-08 08:48:23.652	warn	(13165) This value will not be set in future versions. Please report this to the developer.
deconz.0	2020-05-08 08:48:23.652	warn	(13165) State value to set is invalid for deconz.0.Groups.3.on: The state is missing the required property val!
deconz.0	2020-05-08 08:48:23.651	debug	(13165) Code 200: Request succeded set group state 3: [{"success":{"/groups/3/action/on":false}}]
deconz.0	2020-05-08 08:48:23.639	info	(13165) Terminated (NO_ERROR): Without reason
deconz.0	2020-05-08 08:48:23.638	debug	(13165) Plugin sentry destroyed
deconz.0	2020-05-08 08:48:23.637	info	(13165) terminating
deconz.0	2020-05-08 08:48:23.572	debug	(13165) Websocket connection closed
deconz.0	2020-05-08 08:48:23.561	info	(13165) cleaned everything up...
deconz.0	2020-05-08 08:48:23.559	error	(13165) Error: undefined is not a valid state value at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1581:39 at deconz.setState (/opt/iobroker/node_modules/iobroker.js-control
deconz.0	2020-05-08 08:48:23.545	error	(13165) uncaught exception: undefined is not a valid state value
deconz.0	2020-05-08 08:48:23.543	warn	(13165) This value will not be set in future versions. Please report this to the developer.
deconz.0	2020-05-08 08:48:23.543	warn	(13165) State value to set is invalid for deconz.0.Lights.4.bri: The state is missing the required property val!
deconz.0	2020-05-08 08:48:23.541	debug	(13165) Code 200: Request succeded set light state 4: [{"success":{"/lights/4/state/on":false}},{"success":{"/lights/4/state/bri":0}}]
deconz.0	2020-05-08 08:48:23.319	debug	(13165) dp: on; id:Lights.18 tmp: deconz,0,Lights,18
deconz.0	2020-05-08 08:48:23.318	debug	(13165) stateChange Lights.18 {"val":false,"ack":false,"ts":XXXXXXXX,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":XXXXXXXX}
deconz.0	2020-05-08 08:48:23.318	debug	(13165) dp: on; id:Groups.3 tmp: deconz,0,Groups,3
deconz.0	2020-05-08 08:48:23.317	debug	(13165) stateChange Groups.3 {"val":false,"ack":false,"ts":XXXXXXXX,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":XXXXXXXX}
deconz.0	2020-05-08 08:48:23.310	debug	(13165) dp: on; id:Groups.3 tmp: deconz,0,Groups,3
deconz.0	2020-05-08 08:48:23.309	debug	(13165) stateChange Groups.3 {"val":false,"ack":false,"ts":XXXXXXXX,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":XXXXXXXX}
deconz.0	2020-05-08 08:48:23.244	debug	(13165) Code 200: Request succeded get group attributes 8: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"eta
deconz.0	2020-05-08 08:48:23.237	debug	(13165) Code 200: Request succeded get group attributes 7: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"eta
deconz.0	2020-05-08 08:48:23.232	debug	(13165) Code 200: Request succeded get group attributes 6: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"eta
deconz.0	2020-05-08 08:48:23.227	debug	(13165) Code 200: Request succeded get group attributes 5: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"eta
deconz.0	2020-05-08 08:48:23.221	debug	(13165) Code 200: Request succeded get group attributes 4: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"eta
deconz.0	2020-05-08 08:48:23.213	debug	(13165) Code 200: Request succeded get group attributes 3: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"eta
deconz.0	2020-05-08 08:48:23.204	debug	(13165) Code 200: Request succeded get group attributes 2: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"eta
deconz.0	2020-05-08 08:48:23.197	debug	(13165) Code 200: Request succeded get group attributes 1: {"action":{"bri":127,"colormode":"xy","ct":0,"effect":"none","hue":22084,"on":true,"sat":0,"scene":null,"xy":[0.312718,0.329015]},"devicememb
deconz.0	2020-05-08 08:48:23.109	debug	(13165) dp: bri; id:Lights.4 tmp: deconz,0,Lights,4
deconz.0	2020-05-08 08:48:23.109	debug	(13165) stateChange Lights.4 {"val":0,"ack":false,"ts":XXXXXXXX,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":XXXXXXXX}
deconz.0	2020-05-08 08:48:22.562	info	(13165) Code 404: Ressource not found get devices: []
deconz.0	2020-05-08 08:48:22.556	debug	(13165) Code 200: Request succeded get all groups: {"1":{"action":{"bri":127,"colormode":"xy","ct":0,"effect":"none","hue":22084,"on":true,"sat":0,"scene":null,"xy":[0.312718,0.329015]},"devicemembers
deconz.0	2020-05-08 08:48:22.437	debug	(13165) Code 200: Request succeded get all sensors: {"10":{"config":{"battery":100,"on":true,"reachable":true},"ep":1,"etag":"XXXXXXXX","manufacturername":"LUMI","mode":1,"mode
deconz.0	2020-05-08 08:48:22.260	debug	(13165) Code 200: Request succeded get all lights: {"1":{"ctmax":370,"ctmin":151,"etag":"XXXXXXXX","hascolor":true,"manufacturername":"OSRAM","modelid":"Flex RGBW","name":"Wohn
deconz.0	2020-05-08 08:48:22.240	debug	(13165) Subscribed to updates...
deconz.0	2020-05-08 08:48:22.228	info	(13165) deConz Version: 2.5.67; API version: 1.16.0
deconz.0	2020-05-08 08:48:22.226	debug	(13165) Code 200: Request succeded get config: {"UTC":"2020-05-08T06:48:22","apiversion":"1.16.0","backup":{"errorcode":0,"status":"idle"},"bridgeid":"XXXXXXXX","datastoreversion":"60","devic
deconz.0	2020-05-08 08:48:22.117	info	(13165) starting. Version 1.3.7 in /opt/iobroker/node_modules/iobroker.deconz, node: v12.16.2, js-controller: 3.0.18
deconz.0	2020-05-08 08:48:21.989	debug	(13165) Plugin sentry Initialize Plugin (enabled=true)
```

**Noch eine Ergänzung:
Habe Version 1.3.5 auch versucht, diese lief auch nicht.
Habe dann noch eine node Update auf v12.16.3 durchgeführt, auch nicht.
Die Objekte habe ich gelöscht und neu erstellt, auch nicht.
Was dann funktioniert hat:
Backup von heute 2:00 Uhr eingespielt und Version 1.3.4 installiert, jetzt läuft zum Glück alles erst mal wieder.**

**Comment by Jey-Cee** [comment]
Bitte darauf achten das wenn ihr js-controller 3 hab der auch die Version 3.0.20 hat.

**Comment by capitaenz** [comment]
@Jey-Cee Der Fehler ist bekannt mit 3.0.18? Dann mache ich mal ein Update auf 3.0.20
Danke für den Hinweis

**Comment by Mr-REM-Esq** [comment]
> Yes correct but wait until tomorrow, there is aproblem with 1.3.6 and i have removed it.
> Tomorrow is 1.3.7 available.

How to install 1.3.7 manually? The system only shows availability of version 1.3.6.

**Comment by capitaenz** [comment]
@Jey-Cee Perfekt, läuft jetzt mit dem Update auf 3.0.20!

@Mr-REM-Esq Maybe switch to "latest"?

![latest](https://user-images.githubusercontent.com/1240236/81406028-1c2b8900-9139-11ea-87c9-a0d86cf32f07.JPG)

**Comment by Mr-REM-Esq** [comment]
> @Jey-Cee Perfekt, läuft jetzt mit dem Update auf 3.0.20!
> 
> @Mr-REM-Esq Maybe switch to "latest"?

So it is already installed.

<img width="463" alt="Снимок экрана 2020-05-08 в 15 36 35" src="https://user-images.githubusercontent.com/42520242/81406289-f8207580-9141-11ea-808c-788557a96bd5.png">

**Comment by Mr-REM-Esq** [comment]
I have use
sudo -u iobroker -H npm install iobroker.deconz@1.3.7

It was installed, but the settings did not appear.

**Comment by Mr-REM-Esq** [comment]
Finally, the system itself saw that version 1.3.7 was available in the repository. Once again, I removed the adapter and reinstalled it. Now everything works.

**Comment by Mr-REM-Esq** [comment]
No, it still doesn’t work. Now deconz does not see the values of the sensors.

<img width="1080" alt="Снимок экрана 2020-05-08 в 17 58 13" src="https://user-images.githubusercontent.com/42520242/81418721-ce714980-9155-11ea-9d79-d6d34fc1b840.png">

**Comment by Mr-REM-Esq** [comment]
Wow. First sensor updated.

<img width="1088" alt="Снимок экрана 2020-05-08 в 18 02 04" src="https://user-images.githubusercontent.com/42520242/81418968-29a33c00-9156-11ea-8793-9b32f05eb9f4.png">
