### ISSUE TITLE
Crash when one specific OSRAM plug is triggered from outside of ioBroker

### ISSUE THREAD

**Issue by Signum** [Jey-Cee/ioBroker.deconz#193]
I have updated to version 2.0.5 because the stable version has so many problems (e.g. renaming of devices) that I found it unusuable.

However I noticed that the adapter crashed if the plug is triggered from an external source. Which means…

* someone presses the button on the plug
* the plug is triggered from the legacy "Wireless Light" web application

To make things more confusing this only happens with one specific plug. I cannot reproduce that with others. At first I thought that the plug is somehow broken but at least I can control it from the "Wireless Light" web app.

Although the device is shown in ioBroker I cannot switch it on or off at all.

I have four other OSRAM plugs that work flawlessly.

This is the log output when the adapter runs in 'debug' mode:

```
2020-11-26 23:58:26.209  - debug: deconz.1 (9721) Websocket connection closed
2020-11-26 23:58:26.213  - debug: deconz.1 (9721) Subscribed to updates...
2020-11-26 23:58:51.069  - debug: deconz.1 (9721) Websocket message: {"attr":{"id":"1","lastannounced":null,"lastseen":"2020-11-26T22:58Z","manufacturername":"dresden elektronik","modelid":"ConBee II","name":"Configuration tool 1","swversion":"0x26660700","type":"Configuration tool","uniqueid":"00:21:2e:ff:ff:06:51:3e-01"},"e":"changed","id":"1","r":"lights","t":"event","uniqueid":"00:21:2e:ff:ff:06:51:3e-01"}
2020-11-26 23:59:02.081  - debug: deconz.1 (9721) Websocket message: {"attr":{"id":"9","lastannounced":"2020-11-26T22:54:31Z","lastseen":"2020-11-26T22:59Z","manufacturername":"OSRAM","modelid":"Plug 01","name":"Küche Fenster","swversion":"V1.04.12","type":"On/Off plug-in unit","uniqueid":"84:18:26:00:00:10:19:c2-03"},"e":"changed","id":"9","r":"lights","t":"event","uniqueid":"84:18:26:00:00:10:19:c2-03"}
2020-11-26 23:59:02.082  - debug: deconz.1 (9721) Websocket message: {"e":"changed","id":"9","r":"lights","state":{"on":false,"reachable":true},"t":"event","uniqueid":"84:18:26:00:00:10:19:c2-03"}
2020-11-26 23:59:02.086  - debug: deconz.1 (9721) Websocket message: {"e":"changed","id":"65520","r":"groups","state":{"all_on":false,"any_on":true},"t":"event"}
2020-11-26 23:59:02.087  - debug: deconz.1 (9721) Websocket message: {"e":"changed","id":"2","r":"groups","state":{"all_on":false,"any_on":false},"t":"event"}
2020-11-26 23:59:02.099  - error: deconz.1 (9721) unhandled promise rejection: Cannot read property 'id' of undefined
2020-11-26 23:59:02.101  - error: deconz.1 (9721) TypeError: Cannot read property 'id' of undefined
    at handleWSmessage (/opt/iobroker/node_modules/iobroker.deconz/main.js:2325:54)
2020-11-26 23:59:02.103  - info: deconz.1 (9721) cleaned everything up...
2020-11-26 23:59:02.108  - debug: deconz.1 (9721) Websocket connection closed
2020-11-26 23:59:02.109  - debug: deconz.1 (9721) Code 200: Request succeded get group attributes 65520: {"action":{"alert":"alert","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"etag":"cb2a727dd2695f4632d0466ce9294771","id":"65520","lights":["6","3","1","4","8","9"],"name":"All","scenes":[],"state":{"all_on":false,"any_on":true},"type":"LightGroup"}
2020-11-26 23:59:02.109  - debug: deconz.1 (9721) Code 200: Request succeded get group attributes 2: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"etag":"cb2a727dd2695f4632d0466ce9294771","id":"2","lights":["9"],"name":"Küche","scenes":[],"state":{"all_on":false,"any_on":false},"type":"LightGroup"}
2020-11-26 23:59:02.118  - info: deconz.1 (9721) terminating
2020-11-26 23:59:02.118  - debug: deconz.1 (9721) Plugin sentry destroyed
2020-11-26 23:59:02.119  - info: deconz.1 (9721) Terminated (NO_ERROR): Without reason
2020-11-26 23:59:02.630  - error: host.nibbler Caught by controller[1]:     at handleWSmessage (/opt/iobroker/node_modules/iobroker.deconz/main.js:2325:54)
2020-11-26 23:59:02.630  - info: host.nibbler instance system.adapter.deconz.1 terminated with code 0 (NO_ERROR)
2020-11-26 23:59:02.630  - info: host.nibbler Restart adapter system.adapter.deconz.1 because enabled
```

**Comment by Jey-Cee** [comment]
Development of verion 2 stopped, this is no longer relevant.
For more information (German) look into: https://forum.iobroker.net/topic/39627/deconz-aadapter-beta-ist-zustand-und-zukunft
