### ISSUE TITLE
Adapter crashes when turning lights on/off

### ISSUE THREAD

**Issue by mrfenyx** [Jey-Cee/ioBroker.deconz#240]
I'm using a script to turn light groups on/off. I tried this by setting the .on property directly to true/false and also by using the .action and setting it to '"on": true' or '"on"; false'.  The script used to work without any issues until maybe 2-3 weeks ago. I am using version 2.0.5 of the adapter. deConz Version: 2.10.4; API Version: 1.16.0

Here are the logs:
```
2021-05-17 21:23:49.188  - [32minfo[39m: javascript.0 (20750) script.js.Lights.Living_Room_Light: Turning off the lights!
2021-05-17 21:23:49.426  - [33mwarn[39m: deconz.0 (2604) State value to set for "deconz.0.groups.65520.ct" has value "0" less than min "250"
2021-05-17 21:23:49.470  - [33mwarn[39m: deconz.0 (2604) State value to set for "deconz.0.groups.1.ct" has value "0" less than min "250"
2021-05-17 21:23:49.531  - [32minfo[39m: deconz.0 (2604) State value to set for "deconz.0.groups.65520.xy" has to be type "string" but received type "object" 
2021-05-17 21:23:49.542  - [32minfo[39m: deconz.0 (2604) State value to set for "deconz.0.groups.1.xy" has to be type "string" but received type "object" 
2021-05-17 21:23:53.575  - [32minfo[39m: squeezeboxrpc.0 (21666) State value to set for "squeezeboxrpc.0.Server.LastScan" has to be type "number" but received type "string" 
2021-05-17 21:23:56.274  - [31merror[39m: deconz.0 (2604) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-05-17 21:23:56.275  - [31merror[39m: deconz.0 (2604) unhandled promise rejection: Cannot read property 'id' of undefined
2021-05-17 21:23:56.281  - [31merror[39m: deconz.0 (2604) TypeError: Cannot read property 'id' of undefined
    at handleWSmessage (/opt/iobroker/node_modules/iobroker.deconz/main.js:2325:54)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processImmediate (internal/timers.js:434:9)
    at WebSocket.ws.onmessage (/opt/iobroker/node_modules/iobroker.deconz/main.js:614:13)
2021-05-17 21:23:56.282  - [31merror[39m: deconz.0 (2604) Cannot read property 'id' of undefined
2021-05-17 21:23:56.298  - [32minfo[39m: deconz.0 (2604) cleaned everything up...
2021-05-17 21:23:56.299  - [32minfo[39m: deconz.0 (2604) terminating
2021-05-17 21:23:56.300  - [33mwarn[39m: deconz.0 (2604) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-05-17 21:23:56.313  - [33mwarn[39m: deconz.0 (2604) Object of state "deconz.0.info.connection" is missing the required property "common.type"
2021-05-17 21:23:56.447  - [33mwarn[39m: deconz.0 (2604) State value to set for "deconz.0.groups.65520.ct" has value "0" less than min "250"
2021-05-17 21:23:56.552  - [32minfo[39m: deconz.0 (2604) State value to set for "deconz.0.groups.65520.xy" has to be type "string" but received type "object" 
2021-05-17 21:23:56.563  - [32minfo[39m: deconz.0 (2604) State value to set for "deconz.0.groups.13.xy" has to be type "string" but received type "object" 
2021-05-17 21:23:56.913  - [31merror[39m: host.home Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2021-05-17 21:23:56.913  - [31merror[39m: host.home Caught by controller[1]: TypeError: Cannot read property 'id' of undefined
2021-05-17 21:23:56.914  - [31merror[39m: host.home Caught by controller[1]:     at handleWSmessage (/opt/iobroker/node_modules/iobroker.deconz/main.js:2325:54)
2021-05-17 21:23:56.914  - [31merror[39m: host.home Caught by controller[1]:     at runNextTicks (internal/process/task_queues.js:62:5)
2021-05-17 21:23:56.914  - [31merror[39m: host.home Caught by controller[1]:     at processImmediate (internal/timers.js:434:9)
2021-05-17 21:23:56.915  - [31merror[39m: host.home Caught by controller[1]:     at WebSocket.ws.onmessage (/opt/iobroker/node_modules/iobroker.deconz/main.js:614:13)
2021-05-17 21:23:56.915  - [31merror[39m: host.home instance system.adapter.deconz.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-05-17 21:23:56.916  - [32minfo[39m: host.home Restart adapter system.adapter.deconz.0 because enabled
```

Here is my Script:
```
const lightTableDP = "deconz.0.groups.1.action"; //Living Room Table
const lightCouchDP = "deconz.0.groups.13.on";
const lightKitchenDP = "deconz.0.groups.19.on";
const waitTime = 40000;
var timeout;
var logging = true;

on({id: lightCouchDP, change: "ne"}, function (obj) {
    var value = obj.state.val;
    if(!value) {
        TriggerLight();
    };
});

function TriggerLight() {
    var kitchenLight = getState(lightKitchenDP).val;
    logg(" A: " + isAstroDay() + " K: " + kitchenLight);
    if(!isAstroDay() && !kitchenLight){
        logg('Turning on the Living Room table lights!');
        setState(lightTableDP, '"on": true');
        TimeOut();
    };
};

function TimeOut() {
    logg("Setting timeout");
    timeout = setTimeout(function () {
        timeout = null;
        logg('Turning off the lights!');
        setState(lightTableDP, '"on": false');  
    }, waitTime);
};

function logg(message) {
    if(logging) {log(message);}
};
```

Any help / solution is appreciated.

**Comment by Jey-Cee** [comment]
I am sorry but the only help i can offer is to say go to the stable version.

**Comment by mrfenyx** [comment]
Oh man, changing everything back to v. 1 would be a killer with the changed names in the paths (e.g. .Sensors.## vs. .sensors.uid). Are there any plans to update v. 2 anytime soon?

**Comment by Jey-Cee** [comment]
Nope development for v2 is skipped. There is a plan for v3 but not started yet.

**Comment by mrfenyx** [comment]
Well, took me about 4 hours of work but I switched back to v.1...
